name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull madeye11/my-react-app:latest
    - name: Delete Old docker container
      run: sudo docker rm -f my-react-app-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3000:80 --name my-react-app-container madeye11/my-react-app
